# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-sample-app-2:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./template-sample-app-2/template

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp package.dev.json package.json
      - run: npm install -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn cy:ci
        env:
          CI: true

  test-template-base-2-app:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./template-base-2/template

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp package.dev.json package.json
      - run: npm install -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn cy:ci
        env:
          CI: true
